# Generated by Django 2.2.12 on 2021-04-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prdlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('brand_pd', models.CharField(max_length=100)),
                ('pd_details', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
