# Generated by Django 2.2.12 on 2021-04-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_transacr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('brand_pd', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Transacr',
        ),
    ]
