# Generated by Django 2.2.12 on 2021-04-09 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210409_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transact',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
