# Generated by Django 2.2.12 on 2021-04-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_analysis',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
