# Generated by Django 3.2.2 on 2021-05-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_review_enquired'),
    ]

    operations = [
        migrations.AddField(
            model_name='transact',
            name='Quantity',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
