# Generated by Django 3.2.2 on 2021-05-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_transact_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transact',
            name='Quantity',
            field=models.CharField(max_length=100),
        ),
    ]
