# Generated by Django 3.2.2 on 2021-05-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210521_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Total_Price',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
