# Generated by Django 3.2.5 on 2021-07-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_cart_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdlist',
            name='stock',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
