# Generated by Django 3.2.5 on 2021-07-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_prdlist_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdlist',
            name='stock',
            field=models.IntegerField(max_length=500),
        ),
    ]
