# Generated by Django 3.2.5 on 2021-07-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_prdlist_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdlist',
            name='brand_pd',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
